name: Build artifact

on:
  push:
    branches:
      - 'fix/**'
  workflow_dispatch:

env:
  SolastaInstallDir: ../SolastaFiles

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore SolastaUnfinishedBusiness.sln
      - name: Clean
        run: dotnet clean SolastaUnfinishedBusiness.sln
      - name: Build
        run: dotnet build SolastaUnfinishedBusiness.sln --no-restore -c "Release Workflow"
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: SolastaUnfinishedBusiness
          path: ./SolastaFiles/Mods/
          if-no-files-found: error
